### ISSUE TITLE
Exception in thread "main" org.luaj.vm2.LuaError

### ISSUE THREAD

**Issue by kjundada** [only52607/lua-mirai#37]
Exception in thread "main" org.luaj.vm2.LuaError: @aio.lua:357 index expected, got nil                                                        
        at org.luaj.vm2.LuaValue.typerror(LuaValue.java:1073)                                                                                 
        at org.luaj.vm2.LuaValue.settable(LuaValue.java:3329)                                                                                 
        at org.luaj.vm2.LuaValue.set(LuaValue.java:1165)                                                                                      
        at org.luaj.vm2.LuaClosure.execute(LuaClosure.java:250)                                                                               
        at org.luaj.vm2.LuaClosure.call(LuaClosure.java:133)                                                                                  
        at com.ooooonly.luakt.LuaCodeRunnerKt.runLuaFile(LuaCodeRunner.kt:14)                                                                 
        at com.ooooonly.luaMirai.MainKt.execFile(main.kt:21)                                                                                  
        at com.ooooonly.luaMirai.MainKt.main(main.kt:14)                                                                                      
        at com.ooooonly.luaMirai.MainKt$$$main.invoke(Unknown Source)                                                                         
        at kotlin.coroutines.intrinsics.IntrinsicsKt__IntrinsicsJvmKt$createCoroutineUnintercepted$$inlined$createCoroutineFromSuspendFunction$IntrinsicsKt__IntrinsicsJvmKt$1.invokeSuspend(IntrinsicsJvm.kt:199)                                                                          
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)                                             
        at kotlin.coroutines.ContinuationKt.startCoroutine(Continuation.kt:114)                                                               
        at kotlin.coroutines.jvm.internal.RunSuspendKt.runSuspend(RunSuspend.kt:19)                                                           
        at com.ooooonly.luaMirai.MainKt.main(main.kt)

**Comment by only52607** [comment]
> Exception in thread "main" org.luaj.vm2.LuaError: @aio.lua:357 index expected, got nil
> at org.luaj.vm2.LuaValue.typerror(LuaValue.java:1073)
> at org.luaj.vm2.LuaValue.settable(LuaValue.java:3329)
> at org.luaj.vm2.LuaValue.set(LuaValue.java:1165)
> at org.luaj.vm2.LuaClosure.execute(LuaClosure.java:250)
> at org.luaj.vm2.LuaClosure.call(LuaClosure.java:133)
> at com.ooooonly.luakt.LuaCodeRunnerKt.runLuaFile(LuaCodeRunner.kt:14)
> at com.ooooonly.luaMirai.MainKt.execFile(main.kt:21)
> at com.ooooonly.luaMirai.MainKt.main(main.kt:14)
> at com.ooooonly.luaMirai.MainKt$$$main.invoke(Unknown Source)
> at kotlin.coroutines.intrinsics.IntrinsicsKt__IntrinsicsJvmKt$createCoroutineUnintercepted$$inlined$createCoroutineFromSuspendFunction$IntrinsicsKt__IntrinsicsJvmKt$1.invokeSuspend(IntrinsicsJvm.kt:199)
> at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
> at kotlin.coroutines.ContinuationKt.startCoroutine(Continuation.kt:114)
> at kotlin.coroutines.jvm.internal.RunSuspendKt.runSuspend(RunSuspend.kt:19)
> at com.ooooonly.luaMirai.MainKt.main(main.kt)

看上去是lua文件的第357行出现了错误，你检查一下。

**Comment by kjundada** [comment]
谢谢
