### ISSUE TITLE
启动时提示“未知的运行参数”

### ISSUE THREAD

**Issue by scvoet** [only52607/lua-mirai#44]
# 环境
- CentOS 7.8.2003 (Core)
- openjdk 1.8.0_272
- OpenJDK Runtime Environment (build 1.8.0_272-b10)
- OpenJDK 64-Bit Server VM (build 25.272-b10, mixed mode)
- Lua-Mirai v1.3.0

# 问题
``` shell
[root@host5979f72101 bot]# java -jar lua-mirai.jar web
Exception in thread "main" java.lang.Exception: 未知的运行参数！
        at com.ooooonly.luaMirai.MainKt.main(main.kt:16)
        at com.ooooonly.luaMirai.MainKt$$$main.invoke(Unknown Source)
        at kotlin.coroutines.intrinsics.IntrinsicsKt__IntrinsicsJvmKt$createCoroutineUnintercepted$$inlined$createCoroutineFromSuspendFunction$IntrinsicsKt__IntrinsicsJvmKt$1.invokeSuspend(IntrinsicsJvm.kt:205)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlin.coroutines.ContinuationKt.startCoroutine(Continuation.kt:115)
        at kotlin.coroutines.jvm.internal.RunSuspendKt.runSuspend(RunSuspend.kt:19)
        at com.ooooonly.luaMirai.MainKt.main(main.kt)
```

另外该如何指定 lua-mirai 的运行端口？

**Comment by only52607** [comment]
请使用 [https://github.com/only52607/miruado](miruado)

**Comment by scvoet** [comment]
> 
> 
> 请使用 [https://github.com/only52607/miruado](miruado)

该如何指定端口号，另外你的 Markdown 写反了（

**Comment by scvoet** [comment]
运行后能在 `config/config.json` 中找到。
