### ISSUE TITLE
Http问题

### ISSUE THREAD

**Issue by Miaow233** [only52607/lua-mirai#51]
使用示例脚本
```Lua
Event.subscribe("GroupMessageEvent", function(event)
    local group = event.group
    local msg = event.message
    if tostring(msg) == "一言" then
        group:sendMessage(Http.get("https://v1.hitokoto.cn/?encode=text"))
    end
end)
```
报错如下
```
2021-02-11 02:33:16 W/stderr: org.luaj.vm2.LuaError: @mirai-scripts/events/MessageEvent.lua:38 vm error: com.ooooonly.luakt.mapper.userdata.ParameterNotMatchException: 2 overload function has been tried as follow,but failed to match the corresponding overloaded function.Please check for incorrect use '.' Operator instead of ':' operator.
2021-02-11 02:33:16 W/stderr:  sendMessage(null:GroupImpl,message:Message) Parameter not match:argument type mismatch
2021-02-11 02:33:16 W/stderr: sendMessage(null:GroupImpl,message:String) Parameter not match:argument type mismatch
2021-02-11 02:33:16 W/stderr:
2021-02-11 02:33:16 W/stderr:   at org.luaj.vm2.LuaClosure.execute(LuaClosure.java:506)
2021-02-11 02:33:16 W/stderr:   at org.luaj.vm2.LuaClosure.onInvoke(LuaClosure.java:178)
2021-02-11 02:33:16 W/stderr:   at org.luaj.vm2.LuaClosure.invoke(LuaClosure.java:171)
2021-02-11 02:33:16 W/stderr:   at com.ooooonly.luaMirai.lua.lib.mirai.EventLib$subscriber$1$3.invokeSuspend(EventLib.kt:64)
2021-02-11 02:33:16 W/stderr:   at com.ooooonly.luaMirai.lua.lib.mirai.EventLib$subscriber$1$3.invoke(EventLib.kt)
2021-02-11 02:33:16 W/stderr:   at net.mamoe.mirai.event.EventChannel$subscribeAlways$1.invokeSuspend(EventChannel.kt:431)
2021-02-11 02:33:16 W/stderr:   at net.mamoe.mirai.event.EventChannel$subscribeAlways$1.invoke(EventChannel.kt)
2021-02-11 02:33:16 W/stderr:   at net.mamoe.mirai.event.EventChannel$filter$1$intercepted$thisIntercepted$1.invokeSuspend(EventChannel.kt:145)
2021-02-11 02:33:16 W/stderr:   at net.mamoe.mirai.event.EventChannel$filter$1$intercepted$thisIntercepted$1.invoke(EventChannel.kt)
2021-02-11 02:33:16 W/stderr:   at net.mamoe.mirai.internal.event.Handler$onEvent$2.invokeSuspend(InternalEventListeners.kt:49)
2021-02-11 02:33:16 W/stderr:   at net.mamoe.mirai.internal.event.Handler$onEvent$2.invoke(InternalEventListeners.kt)
2021-02-11 02:33:16 W/stderr:   at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:91)
2021-02-11 02:33:16 W/stderr:   at kotlinx.coroutines.BuildersKt__Builders_commonKt.withContext(Builders.common.kt:165)
2021-02-11 02:33:16 W/stderr:   at kotlinx.coroutines.BuildersKt.withContext(Unknown Source)
2021-02-11 02:33:16 W/stderr:   at net.mamoe.mirai.internal.event.Handler.onEvent(InternalEventListeners.kt:49)
2021-02-11 02:33:16 W/stderr:   at net.mamoe.mirai.event.EventKt.broadcast(Event.kt:226)
2021-02-11 02:33:16 W/stderr:   at net.mamoe.mirai.internal.network.QQAndroidBotNetworkHandler$handlePacket$7.invokeSuspend(QQAndroidBotNetworkHandler.kt:676)
2021-02-11 02:33:16 W/stderr:   at net.mamoe.mirai.internal.network.QQAndroidBotNetworkHandler$handlePacket$7.invoke(QQAndroidBotNetworkHandler.kt)
2021-02-11 02:33:16 W/stderr:   at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:91)
2021-02-11 02:33:16 W/stderr:   at kotlinx.coroutines.BuildersKt__Builders_commonKt.withContext(Builders.common.kt:165)
2021-02-11 02:33:16 W/stderr:   at kotlinx.coroutines.BuildersKt.withContext(Unknown Source)
2021-02-11 02:33:16 W/stderr:   at net.mamoe.mirai.internal.network.QQAndroidBotNetworkHandler.handlePacket(QQAndroidBotNetworkHandler.kt:669)
2021-02-11 02:33:16 W/stderr:   at net.mamoe.mirai.internal.network.QQAndroidBotNetworkHandler$generifiedParsePacket$2.invokeSuspend(QQAndroidBotNetworkHandler.kt:626)
2021-02-11 02:33:16 W/stderr:   at net.mamoe.mirai.internal.network.QQAndroidBotNetworkHandler$generifiedParsePacket$2.invoke(QQAndroidBotNetworkHandler.kt)
2021-02-11 02:33:16 W/stderr:   at net.mamoe.mirai.internal.network.protocol.packet.KnownPacketFactories.handleIncomingPacket$mirai_core(PacketFactory.kt:289)
2021-02-11 02:33:16 W/stderr:   at net.mamoe.mirai.internal.network.protocol.packet.KnownPacketFactories.parseIncomingPacket(PacketFactory.kt:245)
2021-02-11 02:33:16 W/stderr:   at net.mamoe.mirai.internal.network.QQAndroidBotNetworkHandler.generifiedParsePacket(QQAndroidBotNetworkHandler.kt:617)
2021-02-11 02:33:16 W/stderr:   at net.mamoe.mirai.internal.network.QQAndroidBotNetworkHandler.parsePacket(QQAndroidBotNetworkHandler.kt:612)
2021-02-11 02:33:16 W/stderr:   at net.mamoe.mirai.internal.network.QQAndroidBotNetworkHandler$parsePacketAsync$1.invokeSuspend(QQAndroidBotNetworkHandler.kt:594)
2021-02-11 02:33:16 W/stderr:   at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
2021-02-11 02:33:16 W/stderr:   at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
2021-02-11 02:33:16 W/stderr:   at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
2021-02-11 02:33:16 W/stderr:   at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
2021-02-11 02:33:16 W/stderr:   at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
2021-02-11 02:33:16 W/stderr:   at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
2021-02-11 02:33:16 W/stderr: Caused by: com.ooooonly.luakt.mapper.userdata.ParameterNotMatchException: 2 overload function has been tried as follow,but failed to match the corresponding overloaded function.Please check for incorrect use '.' Operator instead of ':' operator.
2021-02-11 02:33:16 W/stderr:  sendMessage(null:GroupImpl,message:Message) Parameter not match:argument type mismatch
2021-02-11 02:33:16 W/stderr: sendMessage(null:GroupImpl,message:String) Parameter not match:argument type mismatch
2021-02-11 02:33:16 W/stderr:
2021-02-11 02:33:16 W/stderr:   at com.ooooonly.luakt.mapper.userdata.KotlinOverloadFunctionWrapper.onInvoke(KotlinOverloadFunctionWrapper.kt:29)
2021-02-11 02:33:16 W/stderr:   at org.luaj.vm2.lib.VarArgFunction.invoke(VarArgFunction.java:77)
2021-02-11 02:33:16 W/stderr:   at org.luaj.vm2.lib.VarArgFunction.call(VarArgFunction.java:62)
2021-02-11 02:33:16 W/stderr:   at org.luaj.vm2.LuaClosure.execute(LuaClosure.java:360)
2021-02-11 02:33:16 W/stderr:   ... 34 more
```
以及`body,isSuccessful,code,message= Http.get(URL)`
body类型为`ArrayVarargs`？
而且`type(Http.get(URL))`也是`ArrayVarargs`

**Comment by Miaow233** [comment]
```Lua
local body,isSuccessful,code,message = Http.get("https://v1.hitokoto.cn")
print(body)
print(isSuccessful)
print(code)
print(message)
```
返回数据
![Screenshot_20210211032241](https://user-images.githubusercontent.com/57578021/107560598-7ef60780-6c18-11eb-997b-850e4c00f1ba.png)
太怪了

**Comment by only52607** [comment]
userdata的方法调用会涉及到方法重载的问题，底层会判断参数数量是否匹配，这样的形式调用会得到错误的参数数量，故正确的使用方法应该为：
``` lua
local body=Http.get(xxx)
xx.sendMessage(body)
```

**Comment by Miaow233** [comment]
确定是用 `.` 访问`sendMessage` 方法吗
如上，直接 `xx:sendMessage(Http.get(xxx))` 也会报错同样的内容

> userdata的方法调用会涉及到方法重载的问题，底层会判断参数数量是否匹配，这样的形式调用会得到错误的参数数量，故正确的使用方法应该为：
> 
> ```lua
> local body=Http.get(xxx)
> xx.sendMessage(body)
> ```
用此种方法: 
```
2021-02-11 10:17:40 W/stderr: org.luaj.vm2.LuaError: @mirai-scripts/events/GroupEvent.lua:5 vm error: com.ooooonly.luakt.mapper.userdata.ParameterNotMatchException: 2 overload function has been tried as follow,but failed to match the corresponding overloaded function.Please check for incorrect use '.' Operator instead of ':' operator.
2021-02-11 10:17:40 W/stderr:  sendMessage(null:FriendImpl,message:Message) Required 2 args,but 1 was given.
sendMessage(null:FriendImpl,message:String) Required 2 args,but 1 was given.

**Comment by only52607** [comment]
> 确定是用 `.` 访问`sendMessage` 方法吗
> 如上，直接 `xx:sendMessage(Http.get(xxx))` 也会报错同样的内容
> 
> > userdata的方法调用会涉及到方法重载的问题，底层会判断参数数量是否匹配，这样的形式调用会得到错误的参数数量，故正确的使用方法应该为：
> > 
> > ```lua
> > local body=Http.get(xxx)
> > xx.sendMessage(body)
> > ```
> 用此种方法: 
> ```
> 2021-02-11 10:17:40 W/stderr: org.luaj.vm2.LuaError: @mirai-scripts/events/GroupEvent.lua:5 vm error: com.ooooonly.luakt.mapper.userdata.ParameterNotMatchException: 2 overload function has been tried as follow,but failed to match the corresponding overloaded function.Please check for incorrect use '.' Operator instead of ':' operator.
> 2021-02-11 10:17:40 W/stderr:  sendMessage(null:FriendImpl,message:Message) Required 2 args,but 1 was given.
> sendMessage(null:FriendImpl,message:String) Required 2 args,but 1 was given.

打错了，应该用:调用
xx:sendMessage(

**Comment by Miaow233** [comment]
是的，但上面的方法也会报错

**Comment by Miaow233** [comment]
如果只是想获取网络响应内容应该如何操作？

**Comment by only52607** [comment]
> 如果只是想获取网络响应内容应该如何操作？

网络响应内容指什么，如果是只要body字段，用上面的方法赋值一遍就行

**Comment by Miaow233** [comment]
> ```lua
> local body,isSuccessful,code,message = Http.get("https://v1.hitokoto.cn")
> print(body)
> print(isSuccessful)
> print(code)
> print(message)
> ```
> 
> 返回数据
> ![Screenshot_20210211032241](https://user-images.githubusercontent.com/57578021/107560598-7ef60780-6c18-11eb-997b-850e4c00f1ba.png)

如这个   body字段应是string，后面的依次赋值
但实际是所有数据都在body，后面的为nil
body类型为ArrayVarargs

**Comment by only52607** [comment]
> > ```lua
> > local body,isSuccessful,code,message = Http.get("https://v1.hitokoto.cn")
> > print(body)
> > print(isSuccessful)
> > print(code)
> > print(message)
> > ```
> > 
> > 返回数据
> > ![Screenshot_20210211032241](https://user-images.githubusercontent.com/57578021/107560598-7ef60780-6c18-11eb-997b-850e4c00f1ba.png)
> 
> 如这个   body字段应是string，后面的依次赋值
> 但实际是所有数据都在body，后面的为nil
> body类型为ArrayVarargs

可能是bug

**Comment by only52607** [comment]
> > ```lua
> > local body,isSuccessful,code,message = Http.get("https://v1.hitokoto.cn")
> > print(body)
> > print(isSuccessful)
> > print(code)
> > print(message)
> > ```
> > 
> > 
> > 返回数据
> > ![Screenshot_20210211032241](https://user-images.githubusercontent.com/57578021/107560598-7ef60780-6c18-11eb-997b-850e4c00f1ba.png)
> 
> 如这个 body字段应是string，后面的依次赋值
> 但实际是所有数据都在body，后面的为nil
> body类型为ArrayVarargs

检查一下问题是否已解决：[https://github.com/only52607/lua-mirai/releases/tag/v2.0.2](lua-mirai 2.0.2)

**Comment by Miaow233** [comment]
> > > ```lua
> > > local body,isSuccessful,code,message = Http.get("https://v1.hitokoto.cn")
> > > print(body)
> > > print(isSuccessful)
> > > print(code)
> > > print(message)
> > > ```
> > > 
> > > 
> > > 返回数据
> > > ![Screenshot_20210211032241](https://user-images.githubusercontent.com/57578021/107560598-7ef60780-6c18-11eb-997b-850e4c00f1ba.png)
> > 
> > 
> > 如这个 body字段应是string，后面的依次赋值
> > 但实际是所有数据都在body，后面的为nil
> > body类型为ArrayVarargs
> 
> 检查一下问题是否已解决：[lua-mirai 2.0.2](https://github.com/only52607/lua-mirai/releases/tag/v2.0.2)

此版本正常，可以正常输出
